services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: be_informed_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE:-be_informed}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony123}
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "symfony",
          "-psymfony123",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: be_informed_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER:-symfony}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-symfony123}
    ports:
      - "8081:80"
    depends_on:
      - database
  ###< doctrine/doctrine-bundle ###

  mailer:
    image: axllent/mailpit
    container_name: be_informed_mailer
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
